---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: nginx
  namespace: flux-system
spec:
  chart:
    spec:
      verify:
        provider: cosign
        secretRef:
          name: cosign-pub
      chart: nginx
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: demo-charts
  interval: 10m0s
  releaseName: nginx
  targetNamespace: default
